name: CI-CD Pipeline

on:
  push:
    branches: [ "main", "development" ]  # Trigger on pushes to main and development branches
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t supervisor299/devops-test:latest .

      - name: Push the Docker image
        run: docker push supervisor299/devops-test:latest
